export const FETCH_LOGIN = 'FETCH_LOGIN'
export const LOGIN = 'LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'

export const CART_TOGGLE_CART = 'cart/toggleCart' 
export const CART_ADD_CART = 'cart/addCart' 
export const CART_INCREMENT = 'cart/increment' 
export const CART_DECREMENT = 'cart/decrement' 
export const CART_REMOVE = 'cart/remove'
export const CART_CHECK_LOGIN = 'cart/checkLogin'
export const CART_CLEAR_CART = 'cart/clearCart'
export const CART_SET_CART = 'cart/setCart'